# Generated by Django 5.2 on 2026-04-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_remove_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='model_name',
            field=models.CharField(default='BAAI/bge-m3', help_text='具体的嵌入模型名称', max_length=100, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_model_name',
            field=models.CharField(blank=True, default='bge-reranker-v2-m3', help_text='Reranker模型名称', max_length=100, verbose_name='Reranker模型名称'),
        ),
    ]
