# Generated by Codex on 2026-04-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0003_add_batch_execution_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiRecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('page_step', '页面步骤'), ('test_case', '测试用例')], max_length=20, verbose_name='目标类型')),
                ('name', models.CharField(max_length=255, verbose_name='录制名称')),
                ('status', models.CharField(choices=[('recording', '录制中'), ('processing', '处理中'), ('draft', '草稿'), ('materialized', '已落库'), ('failed', '失败'), ('cancelled', '已取消')], default='recording', max_length=20, verbose_name='状态')),
                ('env_config', models.JSONField(blank=True, default=dict, verbose_name='环境配置快照')),
                ('actuator_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='执行器ID')),
                ('base_url', models.TextField(blank=True, null=True, verbose_name='基础URL')),
                ('raw_script', models.TextField(blank=True, null=True, verbose_name='原始录制脚本')),
                ('raw_actions', models.JSONField(blank=True, default=list, verbose_name='原始动作')),
                ('normalized_actions', models.JSONField(blank=True, default=list, verbose_name='归一化动作')),
                ('preview_payload', models.JSONField(blank=True, default=dict, verbose_name='草稿预览')),
                ('artifacts', models.JSONField(blank=True, default=dict, verbose_name='录制产物')),
                ('generated_page_step_ids', models.JSONField(blank=True, default=list, verbose_name='生成的页面步骤ID')),
                ('generated_test_case_id', models.IntegerField(blank=True, null=True, verbose_name='生成的测试用例ID')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长（秒）')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_recording_sessions', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_sessions', to='ui_automation.uimodule', verbose_name='所属模块')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_sessions', to='ui_automation.uipage', verbose_name='所属页面')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_recording_sessions', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '录制会话',
                'verbose_name_plural': '录制会话',
                'ordering': ['-started_at'],
                'db_table': 'ui_recording_session',
            },
        ),
    ]
