from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                ("level", models.PositiveSmallIntegerField(default=1, verbose_name="模块级别")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_api_modules", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="api_automation.apimodule", verbose_name="父模块")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_modules", to="projects.project", verbose_name="所属项目")),
            ],
            options={"verbose_name": "接口模块", "verbose_name_plural": "接口模块", "db_table": "api_module", "ordering": ["project", "level", "name"], "unique_together": {("project", "parent", "name")}},
        ),
        migrations.CreateModel(
            name="ApiEnvironmentConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="环境名称")),
                ("base_url", models.URLField(blank=True, default="", max_length=500, verbose_name="基础 URL")),
                ("headers", models.JSONField(blank=True, default=dict, verbose_name="公共请求头")),
                ("variables", models.JSONField(blank=True, default=dict, verbose_name="环境变量")),
                ("is_default", models.BooleanField(default=False, verbose_name="默认环境")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_api_env_configs", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_env_configs", to="projects.project", verbose_name="所属项目")),
            ],
            options={"verbose_name": "接口环境配置", "verbose_name_plural": "接口环境配置", "db_table": "api_environment_config", "ordering": ["-is_default", "-id"]},
        ),
        migrations.CreateModel(
            name="ApiDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="接口名称")),
                ("method", models.CharField(choices=[("GET", "GET"), ("POST", "POST"), ("PUT", "PUT"), ("PATCH", "PATCH"), ("DELETE", "DELETE"), ("HEAD", "HEAD"), ("OPTIONS", "OPTIONS")], max_length=10, verbose_name="请求方法")),
                ("path", models.CharField(max_length=500, verbose_name="接口路径")),
                ("operation_id", models.CharField(blank=True, default="", max_length=200, verbose_name="Operation ID")),
                ("summary", models.CharField(blank=True, default="", max_length=300, verbose_name="摘要")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                ("parameters", models.JSONField(blank=True, default=list, verbose_name="参数定义")),
                ("request_body", models.JSONField(blank=True, default=dict, verbose_name="请求体定义")),
                ("responses", models.JSONField(blank=True, default=dict, verbose_name="响应定义")),
                ("source", models.CharField(default="manual", max_length=40, verbose_name="来源")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_api_definitions", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="definitions", to="api_automation.apimodule", verbose_name="所属模块")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_definitions", to="projects.project", verbose_name="所属项目")),
            ],
            options={"verbose_name": "接口定义", "verbose_name_plural": "接口定义", "db_table": "api_definition", "ordering": ["-id"], "unique_together": {("project", "method", "path")}},
        ),
        migrations.CreateModel(
            name="ApiPublicData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100, verbose_name="变量名")),
                ("value", models.TextField(blank=True, default="", verbose_name="变量值")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_api_public_data", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_public_data", to="projects.project", verbose_name="所属项目")),
            ],
            options={"verbose_name": "接口公共数据", "verbose_name_plural": "接口公共数据", "db_table": "api_public_data", "ordering": ["-id"], "unique_together": {("project", "key")}},
        ),
        migrations.CreateModel(
            name="ApiScript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="脚本名称")),
                ("script_type", models.CharField(choices=[("pre", "前置脚本"), ("post", "后置脚本")], max_length=10, verbose_name="脚本类型")),
                ("content", models.TextField(blank=True, default="", verbose_name="脚本内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_api_scripts", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("module", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scripts", to="api_automation.apimodule", verbose_name="所属模块")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_scripts", to="projects.project", verbose_name="所属项目")),
            ],
            options={"verbose_name": "接口脚本", "verbose_name_plural": "接口脚本", "db_table": "api_script", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="ApiTestCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="用例名称")),
                ("method", models.CharField(default="GET", max_length=10, verbose_name="请求方法")),
                ("path", models.CharField(max_length=500, verbose_name="接口路径")),
                ("headers", models.JSONField(blank=True, default=dict, verbose_name="请求头")),
                ("query_params", models.JSONField(blank=True, default=dict, verbose_name="Query 参数")),
                ("body", models.JSONField(blank=True, default=dict, verbose_name="请求体")),
                ("pre_script", models.TextField(blank=True, default="", verbose_name="前置脚本")),
                ("post_script", models.TextField(blank=True, default="", verbose_name="后置脚本")),
                ("assertions", models.JSONField(blank=True, default=list, verbose_name="断言")),
                ("extractors", models.JSONField(blank=True, default=list, verbose_name="变量提取")),
                ("status", models.SmallIntegerField(choices=[(0, "未执行"), (1, "执行中"), (2, "成功"), (3, "失败")], default=0, verbose_name="状态")),
                ("result_data", models.JSONField(blank=True, default=dict, verbose_name="最近执行结果")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("source", models.CharField(default="manual", max_length=40, verbose_name="来源")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_api_testcases", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("definition", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="testcases", to="api_automation.apidefinition", verbose_name="接口定义")),
                ("environment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="testcases", to="api_automation.apienvironmentconfig", verbose_name="默认环境")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="testcases", to="api_automation.apimodule", verbose_name="所属模块")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_testcases", to="projects.project", verbose_name="所属项目")),
            ],
            options={"verbose_name": "接口测试用例", "verbose_name_plural": "接口测试用例", "db_table": "api_testcase", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="ApiBatchExecutionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="批次名称")),
                ("status", models.SmallIntegerField(choices=[(0, "待执行"), (1, "执行中"), (2, "全部成功"), (3, "部分失败"), (4, "全部失败")], default=0, verbose_name="状态")),
                ("trigger_type", models.CharField(choices=[("manual", "手动执行"), ("scheduled", "定时执行")], default="manual", max_length=20, verbose_name="触发类型")),
                ("total_cases", models.PositiveIntegerField(default=0, verbose_name="总用例数")),
                ("passed_cases", models.PositiveIntegerField(default=0, verbose_name="成功数")),
                ("failed_cases", models.PositiveIntegerField(default=0, verbose_name="失败数")),
                ("duration", models.FloatField(blank=True, null=True, verbose_name="耗时秒")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("executor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="api_batch_records", to=settings.AUTH_USER_MODEL, verbose_name="执行人")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_batch_records", to="projects.project", verbose_name="所属项目")),
            ],
            options={"db_table": "api_batch_execution_record", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="ApiExecutionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.SmallIntegerField(choices=[(0, "未执行"), (1, "执行中"), (2, "成功"), (3, "失败")], default=0, verbose_name="状态")),
                ("trigger_type", models.CharField(choices=[("manual", "手动执行"), ("scheduled", "定时执行")], default="manual", max_length=20, verbose_name="触发类型")),
                ("request_data", models.JSONField(blank=True, default=dict, verbose_name="请求数据")),
                ("response_data", models.JSONField(blank=True, default=dict, verbose_name="响应数据")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("duration", models.FloatField(blank=True, null=True, verbose_name="耗时秒")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="execution_records", to="api_automation.apibatchexecutionrecord", verbose_name="批次")),
                ("environment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="execution_records", to="api_automation.apienvironmentconfig", verbose_name="环境")),
                ("executor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="api_execution_records", to=settings.AUTH_USER_MODEL, verbose_name="执行人")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_execution_records", to="projects.project", verbose_name="所属项目")),
                ("test_case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_records", to="api_automation.apitestcase", verbose_name="接口用例")),
            ],
            options={"db_table": "api_execution_record", "ordering": ["-id"]},
        ),
    ]
