# Generated by Django 5.2 on 2026-07-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0006_apienvironmentconfig_env_type'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='数据驱动：{"ver":["v1","v2"], "user-pwd":[["u1","p1"],["u2","p2"]]}，多参数取笛卡尔积', verbose_name='参数化数据'),
        ),
        migrations.CreateModel(
            name='ApiCustomFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='函数名')),
                ('code', models.TextField(help_text='使用 def 定义函数；模块内所有函数均会被注册，函数名即调用名', verbose_name='Python 代码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_custom_functions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_custom_functions', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口自定义函数',
                'verbose_name_plural': '接口自定义函数',
                'db_table': 'api_custom_function',
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
